"""Generate historical match scores for a model config.

Example:
    MYSQL_HOST=127.0.0.1 MYSQL_PORT=3308 PYTHONPATH=backend \
      backend/.venv/bin/python -m app.scripts.score_history \
      --model default --start 2024-09-28 --end 2026-04-22

V3.2 filtered candidate scores are generated by:
    python -m app.scripts.v31_combination_candidate_backtest --version v32
"""

from __future__ import annotations

import argparse
from datetime import date, datetime, time

from sqlalchemy import and_

from app.core.database import SessionLocal
from app.engine.service import ScoringService
from app.models import (
    ModelConfig,
    SportteryMatch,
    SportteryMatchResult,
    SportteryMatchTeamStats,
)


def _parse_date(value: str) -> date:
    return datetime.strptime(value, "%Y-%m-%d").date()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model", required=True, help="ModelConfig.name to score")
    parser.add_argument("--start", required=True, help="Start date, YYYY-MM-DD")
    parser.add_argument("--end", required=True, help="End date, YYYY-MM-DD")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    start_dt = datetime.combine(_parse_date(args.start), time.min)
    end_dt = datetime.combine(_parse_date(args.end), time.max)

    with SessionLocal() as db:
        cfg = db.query(ModelConfig).filter(ModelConfig.name == args.model).one()
        matches = (
            db.query(SportteryMatch)
            .join(SportteryMatchResult, SportteryMatchResult.match_id == SportteryMatch.id)
            .join(SportteryMatchTeamStats, SportteryMatchTeamStats.match_id == SportteryMatch.id)
            .filter(
                and_(
                    SportteryMatch.match_date >= start_dt,
                    SportteryMatch.match_date <= end_dt,
                )
            )
            .order_by(SportteryMatch.match_date.asc())
            .all()
        )

        svc = ScoringService(db)
        scored = 0
        recommended = 0
        for match in matches:
            score = svc.compute_for_match(match.id, cfg.id)
            if score is None:
                continue
            scored += 1
            if score.is_recommended:
                recommended += 1
        db.commit()

        print(
            f"model={cfg.name} matches={len(matches)} "
            f"scored={scored} recommended={recommended}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
