"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-04-21 15:53:10.754903

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "leagues",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("country", sa.String(length=64), nullable=True),
        sa.Column(
            "draw_rate_tier",
            sa.Enum("high", "medium", "low", name="draw_rate_tier"),
            nullable=True,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "country", name="uq_league_name_country"),
    )
    op.create_index(op.f("ix_leagues_name"), "leagues", ["name"], unique=False)
    op.create_table(
        "scrape_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "source",
            sa.Enum("sporttery", "titan007", "other", name="scrape_source"),
            nullable=False,
        ),
        sa.Column("job_name", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum("success", "failed", "partial", name="scrape_status"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("records_count", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scrape_logs_job_name"), "scrape_logs", ["job_name"], unique=False
    )
    op.create_index(
        op.f("ix_scrape_logs_status"), "scrape_logs", ["status"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("role", sa.Enum("admin", "member", name="user_role"), nullable=False),
        sa.Column("password_hash", sa.String(length=128), nullable=False),
        sa.Column("bankroll_cny", sa.DECIMAL(precision=12, scale=2), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_phone"), "users", ["phone"], unique=True)
    op.create_table(
        "matches",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sporttery_match_id", sa.String(length=32), nullable=True),
        sa.Column("match_date", sa.DateTime(), nullable=False),
        sa.Column("league_id", sa.Integer(), nullable=False),
        sa.Column("home_team", sa.String(length=64), nullable=False),
        sa.Column("away_team", sa.String(length=64), nullable=False),
        sa.Column("round", sa.String(length=32), nullable=True),
        sa.Column(
            "competition_type",
            sa.Enum(
                "league",
                "cup",
                "knockout_first_leg",
                "knockout_second_leg",
                name="competition_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("scheduled", "in_progress", "finished", name="match_status"),
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["league_id"], ["leagues.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_matches_date_league", "matches", ["match_date", "league_id"], unique=False
    )
    op.create_index(
        op.f("ix_matches_league_id"), "matches", ["league_id"], unique=False
    )
    op.create_index(
        op.f("ix_matches_match_date"), "matches", ["match_date"], unique=False
    )
    op.create_index(
        op.f("ix_matches_sporttery_match_id"),
        "matches",
        ["sporttery_match_id"],
        unique=True,
    )
    op.create_index(op.f("ix_matches_status"), "matches", ["status"], unique=False)
    op.create_table(
        "model_configs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("weights_json", sa.JSON(), nullable=False),
        sa.Column("thresholds_json", sa.JSON(), nullable=False),
        sa.Column("kelly_bands_json", sa.JSON(), nullable=False),
        sa.Column("scrape_schedule_json", sa.JSON(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "backtest_sessions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("model_config_id", sa.Integer(), nullable=False),
        sa.Column("date_from", sa.Date(), nullable=False),
        sa.Column("date_to", sa.Date(), nullable=False),
        sa.Column("total_bets", sa.Integer(), nullable=False),
        sa.Column("hit_count", sa.Integer(), nullable=False),
        sa.Column("hit_rate", sa.DECIMAL(precision=6, scale=4), nullable=False),
        sa.Column("roi", sa.DECIMAL(precision=8, scale=4), nullable=False),
        sa.Column("profit_loss", sa.DECIMAL(precision=14, scale=2), nullable=False),
        sa.Column("results_by_score", sa.JSON(), nullable=True),
        sa.Column("results_by_league", sa.JSON(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["model_config_id"], ["model_configs.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_backtest_sessions_model_config_id"),
        "backtest_sessions",
        ["model_config_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_backtest_sessions_user_id"),
        "backtest_sessions",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "match_odds",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            sa.Enum("sporttery", "titan007", "other", name="odds_source"),
            nullable=False,
        ),
        sa.Column("win_odds", sa.DECIMAL(precision=6, scale=3), nullable=True),
        sa.Column("draw_odds", sa.DECIMAL(precision=6, scale=3), nullable=True),
        sa.Column("lose_odds", sa.DECIMAL(precision=6, scale=3), nullable=True),
        sa.Column("handicap_value", sa.DECIMAL(precision=4, scale=2), nullable=True),
        sa.Column("win_handicap_odds", sa.DECIMAL(precision=6, scale=3), nullable=True),
        sa.Column(
            "draw_handicap_odds", sa.DECIMAL(precision=6, scale=3), nullable=True
        ),
        sa.Column(
            "lose_handicap_odds", sa.DECIMAL(precision=6, scale=3), nullable=True
        ),
        sa.Column("asian_handicap", sa.String(length=32), nullable=True),
        sa.Column("total_goals", sa.DECIMAL(precision=4, scale=2), nullable=True),
        sa.Column("scraped_at", sa.DateTime(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["match_id"], ["matches.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_match_odds_match_id"), "match_odds", ["match_id"], unique=False
    )
    op.create_index(
        "ix_odds_match_source", "match_odds", ["match_id", "source"], unique=False
    )
    op.create_table(
        "match_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("home_score", sa.SmallInteger(), nullable=False),
        sa.Column("away_score", sa.SmallInteger(), nullable=False),
        sa.Column(
            "result",
            sa.Enum("home_win", "draw", "away_win", name="match_result_enum"),
            nullable=False,
        ),
        sa.Column(
            "handicap_result",
            sa.Enum("home_win", "draw", "away_win", name="handicap_result_enum"),
            nullable=True,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["match_id"], ["matches.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("match_id"),
    )
    op.create_table(
        "match_scores",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("model_config_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("euro_score", sa.Integer(), nullable=False),
        sa.Column("asian_score", sa.Integer(), nullable=False),
        sa.Column("goals_score", sa.Integer(), nullable=False),
        sa.Column("intent_score", sa.Integer(), nullable=False),
        sa.Column("compression_score", sa.Integer(), nullable=False),
        sa.Column("team_stats_score", sa.Integer(), nullable=False),
        sa.Column("total_score", sa.Integer(), nullable=False),
        sa.Column(
            "bet_type", sa.Enum("draw", "handicap_draw", name="bet_type"), nullable=True
        ),
        sa.Column("kelly_pct", sa.DECIMAL(precision=5, scale=4), nullable=True),
        sa.Column("is_recommended", sa.Boolean(), nullable=False),
        sa.Column("actual_hit", sa.Boolean(), nullable=True),
        sa.Column("bet_amount", sa.DECIMAL(precision=12, scale=2), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["match_id"], ["matches.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["model_config_id"], ["model_configs.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_match_scores_is_recommended"),
        "match_scores",
        ["is_recommended"],
        unique=False,
    )
    op.create_index(
        op.f("ix_match_scores_match_id"), "match_scores", ["match_id"], unique=False
    )
    op.create_index(
        op.f("ix_match_scores_model_config_id"),
        "match_scores",
        ["model_config_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_match_scores_total_score"),
        "match_scores",
        ["total_score"],
        unique=False,
    )
    op.create_index(
        op.f("ix_match_scores_user_id"), "match_scores", ["user_id"], unique=False
    )
    op.create_index(
        "ix_scores_match_config",
        "match_scores",
        ["match_id", "model_config_id"],
        unique=False,
    )
    op.create_table(
        "match_team_stats",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("home_rank", sa.SmallInteger(), nullable=True),
        sa.Column("home_season_wins", sa.SmallInteger(), nullable=True),
        sa.Column("home_season_draws", sa.SmallInteger(), nullable=True),
        sa.Column("home_season_losses", sa.SmallInteger(), nullable=True),
        sa.Column("home_home_wins", sa.SmallInteger(), nullable=True),
        sa.Column("home_home_draws", sa.SmallInteger(), nullable=True),
        sa.Column("home_home_losses", sa.SmallInteger(), nullable=True),
        sa.Column("home_recent_form", sa.String(length=16), nullable=True),
        sa.Column("away_rank", sa.SmallInteger(), nullable=True),
        sa.Column("away_season_wins", sa.SmallInteger(), nullable=True),
        sa.Column("away_season_draws", sa.SmallInteger(), nullable=True),
        sa.Column("away_season_losses", sa.SmallInteger(), nullable=True),
        sa.Column("away_away_wins", sa.SmallInteger(), nullable=True),
        sa.Column("away_away_draws", sa.SmallInteger(), nullable=True),
        sa.Column("away_away_losses", sa.SmallInteger(), nullable=True),
        sa.Column("away_recent_form", sa.String(length=16), nullable=True),
        sa.Column("h2h_home_wins", sa.SmallInteger(), nullable=True),
        sa.Column("h2h_draws", sa.SmallInteger(), nullable=True),
        sa.Column("h2h_away_wins", sa.SmallInteger(), nullable=True),
        sa.Column("scraped_at", sa.DateTime(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["match_id"], ["matches.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("match_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table("match_team_stats")
    op.drop_table("match_scores")
    op.drop_table("match_results")
    op.drop_table("match_odds")
    op.drop_table("backtest_sessions")
    op.drop_table("model_configs")
    op.drop_table("matches")
    op.drop_table("users")
    op.drop_table("scrape_logs")
    op.drop_table("leagues")
