"""Online evaluator for the empirical V3.2 filtered candidate model.

The historical V3.2 scores were generated by
``app.scripts.v31_combination_candidate_backtest``.  This module mirrors the
production-relevant V3.2 rules without depending on the offline report script,
so today's scoring uses the same rule semantics as the imported history.
"""

from __future__ import annotations

from dataclasses import dataclass
from decimal import Decimal
from typing import Any


@dataclass(frozen=True)
class EmpiricalV32Decision:
    rule_name: str
    bet_type: str
    total_score: int
    kelly_pct: Decimal


def _float(value: Any) -> float | None:
    if value is None:
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _sum_ints(*values: int | None) -> int:
    return sum(value or 0 for value in values)


def _rate(numerator: int | float | None, denominator: int | float | None) -> float | None:
    if numerator is None or denominator is None or denominator <= 0:
        return None
    return float(numerator) / float(denominator)


def _form_rate(form: str | None, char: str) -> float | None:
    if not form:
        return None
    text = form.upper()
    return text.count(char) / len(text) if text else None


def _between(value: float | int | None, low: float, high: float) -> bool:
    return value is not None and low <= float(value) <= high


def _ge(value: float | int | None, threshold: float) -> bool:
    return value is not None and float(value) >= threshold


def _le(value: float | int | None, threshold: float) -> bool:
    return value is not None and float(value) <= threshold


def _value(obj: Any, name: str) -> Any:
    return getattr(obj, name, None) if obj is not None else None


def _features(*, match: Any, odds: Any, stats: Any) -> dict[str, Any]:
    hcap = _float(_value(odds, "handicap_value"))
    had_d = _float(_value(match, "had_d"))
    if had_d is None:
        had_d = _float(_value(odds, "draw_odds"))
    hhad_d = _float(_value(match, "hhad_d"))
    if hhad_d is None:
        hhad_d = _float(_value(odds, "draw_handicap_odds"))

    home_season_total = _sum_ints(
        _value(stats, "home_season_wins"),
        _value(stats, "home_season_draws"),
        _value(stats, "home_season_losses"),
    )
    away_season_total = _sum_ints(
        _value(stats, "away_season_wins"),
        _value(stats, "away_season_draws"),
        _value(stats, "away_season_losses"),
    )
    home_venue_total = _sum_ints(
        _value(stats, "home_home_wins"),
        _value(stats, "home_home_draws"),
        _value(stats, "home_home_losses"),
    )
    away_venue_total = _sum_ints(
        _value(stats, "away_away_wins"),
        _value(stats, "away_away_draws"),
        _value(stats, "away_away_losses"),
    )
    h2h_total = _sum_ints(
        _value(stats, "h2h_home_wins"),
        _value(stats, "h2h_draws"),
        _value(stats, "h2h_away_wins"),
    )

    home_season_draw = _rate(_value(stats, "home_season_draws"), home_season_total)
    away_season_draw = _rate(_value(stats, "away_season_draws"), away_season_total)
    home_venue_draw = _rate(_value(stats, "home_home_draws"), home_venue_total)
    away_venue_draw = _rate(_value(stats, "away_away_draws"), away_venue_total)
    home_recent_draw = _form_rate(_value(stats, "home_recent_form"), "D")
    away_recent_draw = _form_rate(_value(stats, "away_recent_form"), "D")
    home_low = _rate(
        _value(stats, "home_recent_low_scoring_count"),
        _value(stats, "home_recent_matches_count"),
    )
    away_low = _rate(
        _value(stats, "away_recent_low_scoring_count"),
        _value(stats, "away_recent_matches_count"),
    )

    home_rank = _value(stats, "home_rank")
    away_rank = _value(stats, "away_rank")
    rank_gap = (
        abs(home_rank - away_rank)
        if home_rank is not None and away_rank is not None
        else None
    )

    return {
        "abs_hcap": abs(hcap) if hcap is not None else None,
        "had_d": had_d,
        "hhad_d": hhad_d,
        "rank_gap": rank_gap,
        "season_draw_sum": (
            home_season_draw + away_season_draw
            if home_season_draw is not None and away_season_draw is not None
            else None
        ),
        "venue_draw_sum": (
            home_venue_draw + away_venue_draw
            if home_venue_draw is not None and away_venue_draw is not None
            else None
        ),
        "recent_draw_sum": (
            home_recent_draw + away_recent_draw
            if home_recent_draw is not None and away_recent_draw is not None
            else None
        ),
        "h2h_draw_rate": _rate(_value(stats, "h2h_draws"), h2h_total),
        "h2h_one_goal_margin_rate": _rate(
            _value(stats, "h2h_one_goal_margin_count"),
            _value(stats, "h2h_matches_count"),
        ),
        "recent_low_scoring_sum": (
            home_low + away_low if home_low is not None and away_low is not None else None
        ),
    }


def _hdraw_v32_core(row: dict[str, Any]) -> bool:
    return (
        _between(row.get("abs_hcap"), 1.00, 1.25)
        and _between(row.get("rank_gap"), 6, 15)
        and _ge(row.get("hhad_d"), 3.50)
        and _ge(row.get("venue_draw_sum"), 0.35)
        and _ge(row.get("season_draw_sum"), 0.35)
    )


def _draw_v31_d(row: dict[str, Any]) -> bool:
    return (
        _ge(row.get("h2h_draw_rate"), 0.35)
        and _ge(row.get("recent_draw_sum"), 0.50)
        and _ge(row.get("recent_low_scoring_sum"), 1.00)
        and _le(row.get("abs_hcap"), 0.50)
        and _between(row.get("had_d"), 3.00, 3.60)
    )


def _draw_v31_b(row: dict[str, Any]) -> bool:
    return (
        _ge(row.get("h2h_one_goal_margin_rate"), 0.35)
        and _ge(row.get("recent_low_scoring_sum"), 1.00)
        and _le(row.get("abs_hcap"), 0.75)
        and row.get("had_d") is not None
    )


def _draw_v32_core(row: dict[str, Any]) -> bool:
    return (_draw_v31_d(row) or _draw_v31_b(row)) and _ge(row.get("had_d"), 3.10)


def empirical_v32_decision(
    *, match: Any, odds: Any, stats: Any
) -> EmpiricalV32Decision | None:
    """Return the V3.2 recommendation for a match, if any.

    Let handicap-draw win when both channels match, mirroring the offline
    portfolio priority where hdraw gets a channel boost over draw.
    """
    row = _features(match=match, odds=odds, stats=stats)
    if _hdraw_v32_core(row):
        return EmpiricalV32Decision(
            rule_name="HDRAW_V32_CORE",
            bet_type="handicap_draw",
            total_score=116,
            kelly_pct=Decimal("0.0150"),
        )
    if _draw_v32_core(row):
        return EmpiricalV32Decision(
            rule_name="DRAW_V32_CORE",
            bet_type="draw",
            total_score=108,
            kelly_pct=Decimal("0.0100"),
        )
    return None
